import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Cube Tools</h1>
      <ul>
        <li>
          <Link href="/commutator">
            <a className="link-hover">Commutator Expander</a>
          </Link>
        </li>
        <li>
          <Link href="/three-style/edge">
            <a className="link-hover">Edge 3-Style</a>
          </Link>
        </li>
        <li>
          <Link href="/three-style/corner">
            <a className="link-hover">Corner 3-Style</a>
          </Link>
        </li>
      </ul>
    </>
  );
};

export default Home;
